In [1]:
import sqlite3
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
os.getcwd()

'C:\\Users\\Tom\\Documents\\Project working directory\\Coursework\\Python files'

In [3]:
os.chdir('~\\Project working directory\\Coursework\\Python files')

FileNotFoundError: [WinError 3] The system cannot find the path specified: '~\\Project working directory\\Coursework\\Python files'

# Creating Database

In [4]:
try:
    os.remove('../Python files/py_airline4.db')
except OSError:
    pass

conn = sqlite3.connect('../Python files/py_+airline4.db')

# Creating table using airline data from 2001 to 2002

In [5]:
planes = pd.read_csv("../dataverse_files/plane-data.csv")
planes.to_sql('planes', con = conn, index = False)

In [6]:
c = conn.cursor()

In [7]:
c.execute('''
CREATE TABLE arrived (
  Year int,
  Month int,
  DayofMonth int,
  DayOfWeek int,
  DepTime  int,
  CRSDepTime int,
  ArrTime int,
  CRSArrTime int,
  UniqueCarrier varchar(5),
  FlightNum int,
  TailNum varchar(8),
  ActualElapsedTime int,
  CRSElapsedTime int,
  AirTime int,
  ArrDelay int,
  DepDelay int,
  Origin varchar(3),
  Dest varchar(3),
  Distance int,
  TaxiIn int,
  TaxiOut int,
  Cancelled int,
  CancellationCode varchar(1),
  Diverted varchar(1),
  CarrierDelay int,
  WeatherDelay int,
  NASDelay int,
  SecurityDelay int,
  LateAircraftDelay int
)
''')

conn.commit()

In [8]:
for year in range(2001, 2002):
    print('Processing: ', year)
    arrived1 = pd.read_csv("../Python files/"+str(year)+".csv.bz2", encoding='latin-1')    
    arrived1.to_sql('arrived1', con = conn, if_exists = 'append', index = False)
for year in range(2002, 2003):
    print('Processing: ', year)
    arrived2 = pd.read_csv("../Python files/"+str(year)+".csv.bz2", encoding='latin-1')    
    arrived2.to_sql('arrived2', con = conn, if_exists = 'append', index = False)
arrived = pd.concat([arrived1, arrived2])
conn.commit()

Processing:  2001
Processing:  2002

# Create dataframe

In [19]:
df1 = c.execute('''
 SELECT TailNum, Year, Month, DayofMonth, DayOfWeek, DepTime, CRSDepTime, ArrTime, CRSArrTime,
 Origin, Dest, ActualElapsedTime, CRSElapsedTime, FlightNum, ArrDelay, DepDelay
 FROM arrived1
 WHERE ArrDelay >0 AND DepDelay>0
 GROUP BY TailNum
 ORDER BY TailNum ASC
             ''').fetchall()
df2 = pd.DataFrame(df1)
df2.columns = ['TailNum', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime', 'ArrTime', 'CRSArrTime',
 'Origin', 'Dest', 'ActualElapsedTime', 'CRSElapsedTime', 'FlightNum', 'ArrDelay', 'DepDelay']
df2

,TailNum,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,Origin,Dest,ActualElapsedTime,CRSElapsedTime,FlightNum,ArrDelay,DepDelay
0,-N037M,2001,1,18,4,1306.0,1255,1400.0,1345,EYW,MIA,54.0,50,5212,15.0,11.0
1,-N047M,2001,1,3,3,1056.0,1045,1153.0,1133,MIA,APF,57.0,48,5201,20.0,11.0
2,-N107D,2001,1,1,1,2221.0,1720,50.0,1940,LAS,SLC,89.0,80,670,310.0,301.0
3,-N108D,2001,1,24,3,533.0,530,728.0,718,FLL,ATL,115.0,108,624,10.0,3.0
4,-N109D,2001,1,5,5,538.0,530,727.0,718,FLL,ATL,109.0,108,624,9.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4551,NR78A1,2001,1,5,5,1020.0,1015,1203.0,1144,LAS,SJC,103.0,89,129,19.0,5.0
4552,NR79A1,2001,1,10,3,1017.0,1015,1207.0,1144,LAS,SJC,110.0,89,129,23.0,2.0
4553,NR80A1,2001,1,7,7,1102.0,1015,1229.0,1144,LAS,SJC,87.0,89,129,45.0,47.0
4554,NR81A1,2001,1,1,1,1207.0,1135,1325.0,1257,SJC,LAS,78.0,82,128,28.0,32.0
4555,NR82A1,2001,1,12,5,1231.0,1135,1406.0,1257,SJC,LAS,95.0,82,128,69.0,56.0

In [11]:
#Find Timing with most delays
df2.TailNum.value_counts().idxmax()

'NR82A1'

In [29]:
#Create a table to visualise flights in a day
df3 = df2.loc[df2['Month'] == 1]
df4 = df3.loc[df3['DayofMonth'] == 1]
df5 = df4.loc[df4['DayOfWeek'] == 1] 

df6 = df5.sort_values(by=['FlightNum'],)
df6.head(n=60)

,TailNum,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,Origin,Dest,ActualElapsedTime,CRSElapsedTime,FlightNum,ArrDelay,DepDelay
1833,N373A1,2001,1,1,1,1000.0,900,1242.0,1211,JFK,LAX,342.0,371,1,31.0,60.0
751,N13088,2001,1,1,1,941.0,940,1358.0,1355,IAH,HNL,497.0,495,1,3.0,1.0
1911,N385A1,2001,1,1,1,1205.0,1200,2028.0,2022,LAX,JFK,323.0,322,4,6.0,5.0
4395,N951ä@,2001,1,1,1,1553.0,1535,1834.0,1830,MIA,JFK,161.0,175,4,4.0,18.0
692,N10834,2001,1,1,1,1726.0,1720,1823.0,1816,IAH,SAT,57.0,56,5,7.0,6.0
4466,N972ãæ,2001,1,1,1,2127.0,2030,1.0,2317,MIA,JFK,154.0,167,6,44.0,57.0
3473,N725ãæ,2001,1,1,1,2215.0,2100,51.0,2352,SJU,JFK,216.0,232,9,59.0,75.0
1551,N322A1,2001,1,1,1,2202.0,2200,633.0,617,LAX,JFK,331.0,317,10,16.0,2.0
3434,N718ãæ,2001,1,1,1,1219.0,1210,1745.0,1737,SNA,STL,206.0,207,10,8.0,9.0
1541,N320A1,2001,1,1,1,1304.0,1300,2157.0,2123,LAX,BOS,353.0,323,12,34.0,4.0
2264,N461ä1,2001,1,1,1,752.0,750,1603.0,1550,SEA,JFK,311.0,300,12,13.0,2.0
2939,N602ä1,2001,1,1,1,1401.0,1400,2207.0,2205,LAX,JFK,306.0,305,14,2.0,1.0
851,N15069,2001,1,1,1,914.0,815,1447.0,1355,EWR,HNL,633.0,640,15,52.0,59.0
1521,N316A1,2001,1,1,1,1322.0,1240,2205.0,2102,SFO,JFK,343.0,322,16,63.0,42.0
3289,N674@@,2001,1,1,1,947.0,940,1046.0,1040,MAF,DAL,59.0,60,19,6.0,7.0
706,N11612,2001,1,1,1,2029.0,2015,2203.0,2200,EWR,RDU,94.0,105,19,3.0,14.0
631,EI`Bæ4,2001,1,1,1,1735.0,1730,1937.0,1927,FLL,STL,182.0,177,19,10.0,5.0
3165,N643ä1,2001,1,1,1,1238.0,1235,2102.0,2055,SFO,JFK,324.0,320,20,7.0,3.0
1418,N301A1,2001,1,1,1,1547.0,1545,18.0,2358,SFO,JFK,331.0,313,20,20.0,2.0
1040,N18835,2001,1,1,1,1606.0,1555,1724.0,1715,EWR,BOS,78.0,80,21,9.0,11.0
4456,N967ãæ,2001,1,1,1,2253.0,2245,2344.0,2336,PDX,SEA,51.0,51,24,8.0,8.0
758,N13248,2001,1,1,1,846.0,830,1721.0,1648,SFO,EWR,335.0,318,24,33.0,16.0
488,-N826A,2001,1,1,1,1503.0,1500,1537.0,1535,HNL,OGG,34.0,35,26,2.0,3.0
2091,N406ä1,2001,1,1,1,2248.0,2200,642.0,553,LAX,PHL,294.0,293,28,49.0,48.0
997,N17812,2001,1,1,1,1246.0,1245,1827.0,1819,DEN,EWR,221.0,214,28,8.0,1.0
1624,N333@@,2001,1,1,1,1450.0,1445,1549.0,1535,HOU,HRL,59.0,50,29,14.0,5.0
4012,N830ä1,2001,1,1,1,1902.0,1810,2135.0,2109,PHL,LAX,333.0,359,29,26.0,52.0
4007,N829ä1,2001,1,1,1,802.0,800,1626.0,1623,SFO,PHL,324.0,323,30,3.0,2.0
1885,N379A1,2001,1,1,1,831.0,800,1649.0,1618,LAX,JFK,318.0,318,34,31.0,31.0
2940,N60312,2001,1,1,1,1600.0,1530,1721.0,1658,IAH,DEN,141.0,148,35,23.0,30.0
4443,N96301,2001,1,1,1,1145.0,1140,1354.0,1351,STL,LAX,249.0,251,37,3.0,5.0
480,-N816A,2001,1,1,1,852.0,850,937.0,928,KOA,HNL,45.0,38,37,9.0,2.0
2849,N5DBA1,2001,1,1,1,957.0,800,1231.0,1120,EWR,LAX,334.0,380,43,71.0,117.0
1889,N380A1,2001,1,1,1,2213.0,1905,8.0,2159,ORD,SFO,235.0,294,47,129.0,188.0
3928,N809Aæ,2001,1,1,1,1345.0,1335,2126.0,2100,LAS,DCA,281.0,265,49,26.0,10.0
3749,N774ä1,2001,1,1,1,825.0,820,1206.0,1155,LAX,HNL,341.0,335,53,11.0,5.0
4351,N939Aâ,2001,1,1,1,1509.0,1505,2046.0,2037,SAN,STL,217.0,212,56,9.0,4.0
3207,N654@@,2001,1,1,1,2205.0,2115,2319.0,2220,DAL,MAF,74.0,65,58,59.0,50.0
1250,N269A1,2001,1,1,1,1757.0,1724,1910.0,1822,DFW,AUS,73.0,58,60,48.0,33.0
3676,N76151,2001,1,1,1,1722.0,1655,2024.0,1948,EWR,IAH,242.0,233,63,36.0,27.0
2481,N509@@,2001,1,1,1,1850.0,1830,1952.0,1935,PHX,ABQ,62.0,65,63,17.0,20.0
818,N14628,2001,1,1,1,1336.0,1334,1706.0,1655,MSY,CLE,150.0,141,66,11.0,2.0
3397,N709Aâ,2001,1,1,1,1643.0,1633,1743.0,1725,KTN,SIT,60.0,52,67,18.0,10.0
3849,N798@@,2001,1,1,1,1419.0,1410,1624.0,1615,BNA,HOU,125.0,125,67,9.0,9.0
4079,N864A1,2001,1,1,1,2249.0,1915,44.0,2127,MIA,DFW,175.0,192,69,197.0,214.0
1315,N29129,2001,1,1,1,1555.0,1540,2038.0,2016,IAH,EWR,223.0,216,70,22.0,15.0
774,N14062,2001,1,1,1,1000.0,955,1332.0,1330,LAX,HNL,332.0,335,75,2.0,5.0
2159,N423ä1,2001,1,1,1,1320.0,1315,1446.0,1439,SNA,SFO,86.0,84,76,7.0,5.0
2100,N408ãæ,2001,1,1,1,1839.0,1835,2100.0,2051,STL,DAY,81.0,76,78,9.0,4.0
3619,N746@@,2001,1,1,1,1545.0,1515,2115.0,2105,LAX,BNA,210.0,230,80,10.0,30.0
2999,N613Aâ,2001,1,1,1,1755.0,1730,2024.0,2004,SEA,ANC,209.0,214,85,20.0,25.0
2638,N538A1,2001,1,1,1,1918.0,1905,2141.0,2140,ORD,LAX,263.0,275,89,1.0,13.0
4467,N973Aâ,2001,1,1,1,1755.0,1314,2130.0,1648,SEA,PHX,155.0,154,92,282.0,281.0
3006,N614Aâ,2001,1,1,1,1703.0,1659,1758.0,1755,ANC,FAI,55.0,56,93,3.0,4.0
2834,N5CJA1,2001,1,1,1,1902.0,1755,2141.0,2101,EWR,DFW,219.0,246,93,40.0,67.0
2560,N523@@,2001,1,1,1,2232.0,2145,2332.0,2245,DAL,LBB,60.0,60,100,47.0,47.0
4487,N979é@,2001,1,1,1,1424.0,1405,1546.0,1531,STL,ICT,82.0,86,101,15.0,19.0
4343,N937Aâ,2001,1,1,1,2000.0,1859,2225.0,2117,LAX,PDX,145.0,138,101,68.0,61.0
3787,N780ä1,2001,1,1,1,1444.0,1155,1636.0,1415,ORD,LAX,232.0,260,117,141.0,169.0
1503,N313Aæ,2001,1,1,1,1026.0,1018,1454.0,1440,PHX,MKE,208.0,202,122,14.0,8.0

In [ ]:
conn.close()